[package]
name = "lightswitch"
version = "0.1.0"
edition = "2021"

[dependencies]
gimli = "*"
object = "*"
memmap2 = "*"
lazy_static = "*"
anyhow = "*"
thiserror = "*"
libbpf-rs = {version = "*", features=["static"]}
num_cpus = "*"
perf-event-open-sys = "*"
libc = "*"
errno = "*"
plain = "*"
procfs = "*"
ring = "*"
data-encoding = "*"
page_size = "*"
clap = { version = "*", features = ["derive"] }
blazesym = "0.2.0-alpha.10"
tracing = "*"
tracing-subscriber = "*"
chrono = "*"
inferno = "*"
rand = "*"

[build-dependencies]
bindgen = "*"
libbpf-cargo = "*"