name: vmtests

on:
    pull_request:
    push:

jobs:
  vmtests:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
        contents: read

    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86-64 qemu-guest-agent qemu-utils ovmf

    - name: Set up nix dev env
      run: nix develop --command echo 0

    - name: Build `lightswitch` statically linked using glibc
      run: nix develop --command bash -c 'RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target x86_64-unknown-linux-gnu'

    - name: Run vmtests
      run: nix develop --command run-vmtests